#version 450
#extension GL_EXT_shader_image_load_formatted : require
#extension GL_EXT_nonuniform_qualifier : require

layout(constant_id = 0) const uint img_width = 0;
layout(constant_id = 1) const uint img_height = 0;

layout(push_constant) uniform PushConstant {
    uint cascades_id;
    uint composite_id;
    float spacing;
    uint probe_size;
} pc;

layout(local_size_x = 8, local_size_y = 8) in;
layout(binding = 0) uniform image2DArray storageImageArraysF[];
layout(binding = 0) uniform image2D storageImagesF[];

ivec2 probe_offsets[] = ivec2[](
        ivec2(0, 0),
        ivec2(1, 0),
        ivec2(0, 1),
        ivec2(1, 1)
);

void main() {
    ivec2 local = ivec2(gl_GlobalInvocationID.xy);
    if (any(greaterThanEqual(local, ivec2(img_width, img_height)))) return;

    vec2 base_coord = (vec2(local) / pc.spacing) - vec2(0.5);
    ivec2 base_index = ivec2(floor(base_coord));
    vec2 ratio = base_coord - vec2(base_index);

    vec4 weights = vec4(
            (1.0 - ratio.x) * (1.0 - ratio.y),
            ratio.x * (1.0 - ratio.y),
            (1.0 - ratio.x) * ratio.y,
            ratio.x * ratio.y
    );

    int dir_count = int(pc.probe_size * pc.probe_size);

    vec4 sum = vec4(0.0);
    for (int i = 0; i < 4; i++)
    {
        vec4 sub_sum = vec4(0.0);
        for (int j = 0; j < dir_count; j++)
        {
            ivec2 offset = probe_offsets[i];
            ivec2 index = base_index + offset;
            ivec2 dir_index = ivec2(j % int(pc.probe_size), j / int(pc.probe_size));
            ivec2 texel = index * int(pc.probe_size) + dir_index;
            sub_sum += imageLoad(storageImageArraysF[pc.cascades_id], ivec3(texel, 0)) * weights[i];
        }
        sum += sub_sum / dir_count;
    }

    imageStore(storageImagesF[pc.composite_id], local, sum);
}