#version 450

layout(local_size_x = 8, local_size_y = 8) in;
layout(binding = 0, rgba16f) uniform image2D img;
layout(binding = 1, rg32i) uniform iimage2D jfa_img;

void main() {
    ivec2 local = ivec2(gl_GlobalInvocationID.xy);
    if (any(greaterThanEqual(local, ivec2(256)))) return;

    vec4 drawn = imageLoad(img, local);

    if (any(greaterThan(drawn, vec4(0.0)))) {
        imageStore(jfa_img, local, ivec4(local, 0, 0));
        return;
    }
    imageStore(jfa_img, local, ivec4(-1, -1, 0, 0));
}