#version 450
#extension GL_EXT_shader_image_load_formatted : require
#extension GL_EXT_nonuniform_qualifier : require

layout(constant_id = 0) const uint img_width = 0;
layout(constant_id = 1) const uint img_height = 0;

layout(push_constant) uniform PushConstant {
    uint jfa_id;
} pushConstants;

layout(local_size_x = 8, local_size_y = 8) in;
layout(binding = 0) uniform iimage2D storageImagesI[];
layout(binding = 0) uniform uimage2D storageImagesU[];

void main() {
    ivec2 local = ivec2(gl_GlobalInvocationID.xy);
    if (any(greaterThanEqual(local, ivec2(img_width, img_height)))) return;

    uint drawn = imageLoad(storageImagesU[0], local).x;

    if (drawn >= 1) {
        imageStore(storageImagesI[pushConstants.jfa_id], local, ivec4(local, 0, 0));
        return;
    }
    imageStore(storageImagesI[pushConstants.jfa_id], local, ivec4(-1, -1, 0, 0));
}