#version 450
#extension GL_EXT_shader_image_load_formatted : require

layout(constant_id = 0) const uint img_width = 0;
layout(constant_id = 1) const uint img_height = 0;

layout(push_constant) uniform PushConstant {
    ivec2 pos;
    ivec2 size;
} pushConstants;

layout(local_size_x = 8, local_size_y = 8) in;
layout(binding = 2) uniform uimage2D storageImagesU[];

void main() {
    ivec2 local = ivec2(gl_GlobalInvocationID.xy);
    if (any(greaterThanEqual(local, pushConstants.size))) return;
    ivec2 coord = local + pushConstants.pos;
    if (any(greaterThanEqual(coord, ivec2(img_width, img_height))) || any(lessThan(coord, ivec2(0)))) return;
    imageStore(storageImagesU[0], coord, ivec4(1));
}