#version 450

layout(constant_id = 0) const uint img_width = 0;
layout(constant_id = 1) const uint img_height = 0;

layout(push_constant) uniform PushConstant {
    uint k;
} pushConstants;

layout(local_size_x = 8, local_size_y = 8) in;
layout(binding = 0, rg32i) uniform iimage2D jfa_imgs[2];

ivec2 directions[] = ivec2[](
        ivec2(0, 0),
        ivec2(0, 1),
        ivec2(1, 1),
        ivec2(1, 0),
        ivec2(1, -1),
        ivec2(0, -1),
        ivec2(-1, -1),
        ivec2(-1, 0),
        ivec2(-1, 1)
);

void main() {
    ivec2 local = ivec2(gl_GlobalInvocationID.xy);
    if (any(greaterThanEqual(local, ivec2(img_width, img_height)))) return;

    ivec2 closest_seed = ivec2(-1);
    int closest_dist = 9999999;
    for (int i = 0; i < 9; i++) {
        ivec2 dir = directions[i] * ivec2(pushConstants.k);
        ivec2 coord = local + dir;
        if (any(greaterThanEqual(coord, ivec2(img_width, img_height))) || any(lessThan(coord, ivec2(0)))) continue;
        ivec2 offset_point = imageLoad(jfa_imgs[0], coord).xy;
        if (offset_point.x < 0) continue;
        ivec2 d = offset_point - local;
        int dist2 = d.x * d.x + d.y * d.y;
        if (dist2 < closest_dist) {
            closest_dist = dist2;
            closest_seed = offset_point;
        }
    }

    imageStore(jfa_imgs[1], local, ivec4(closest_seed, 0.0, 0.0));
}