#version 450
#extension GL_EXT_shader_image_load_formatted : require
#extension GL_EXT_nonuniform_qualifier : require

layout(push_constant) uniform PushConstant {
    uint cascades_id;
    uint cascade;
    uint cascade_width;
    uint cascade_height;
    uint base_probe_size;
} pc;

layout(local_size_x = 8, local_size_y = 8) in;
layout(binding = 0) uniform image2DArray storageImageArraysF[];

ivec2 probe_offsets[] = ivec2[](
        ivec2(0, 0),
        ivec2(1, 0),
        ivec2(0, 1),
        ivec2(1, 1)
);

vec4 get_weights(vec2 ratio) {
    return vec4(
            (1.0 - ratio.x) * (1.0 - ratio.y),
            ratio.x * (1.0 - ratio.y),
            (1.0 - ratio.x) * ratio.y,
            ratio.x * ratio.y
    );
}

ivec2 get_base_index(vec2 center, vec2 target_size, out vec4 weights) {
    vec2 tl_coord = (center / target_size) - vec2(0.5);
    ivec2 base_index = ivec2(floor(tl_coord));
    weights = get_weights(tl_coord - vec2(base_index));
    return base_index;
}

vec4 merge(vec4 n, vec4 n1) {
    const vec3 radiance = n.rgb + (n1.rgb * n.a);
    return vec4(radiance, n.a * n1.a);
}

void main() {
    ivec2 local = ivec2(gl_GlobalInvocationID.xy);
    if (any(greaterThanEqual(local, ivec2(pc.cascade_width, pc.cascade_height)))) return;

    int probe_size = int(pc.base_probe_size) << pc.cascade;
    ivec2 probe = local / probe_size;

    ivec2 dir = local % probe_size;
    int dir_index = dir.y * probe_size + dir.x;

    vec2 probe_center = (vec2(probe) + 0.5) * float(probe_size);
    int probe_size_n1 = int(pc.base_probe_size) << (pc.cascade + 1);

    vec4 weights = vec4(0.0);
    ivec2 base_index = get_base_index(probe_center, vec2(probe_size_n1), weights);

    int base_dir_index = dir_index * 4;

    vec4 n = imageLoad(storageImageArraysF[pc.cascades_id], ivec3(local, pc.cascade));

    vec4 merged = vec4(0.0);
    for (int d = 0; d < 4; d++) {
        vec4 radiance = vec4(0.0);
        for (int p = 0; p < 4; p++) {
            ivec2 offset = probe_offsets[p];
            ivec2 index = base_index + offset;
            int dir_index = base_dir_index + d;
            ivec2 dir_coord = ivec2(
                    dir_index % probe_size_n1,
                    dir_index / probe_size_n1
            );

            ivec2 texel = index * probe_size_n1 + dir_coord;
            vec4 n1 = imageLoad(storageImageArraysF[pc.cascades_id], ivec3(texel, pc.cascade + 1));

            radiance += merge(n, n1) * weights[p];
        }
        merged += radiance / 4.0;
    }

    imageStore(storageImageArraysF[pc.cascades_id], ivec3(local, pc.cascade), merged);
}