#version 450
#extension GL_EXT_shader_image_load_formatted : require
#extension GL_EXT_nonuniform_qualifier : require

layout(constant_id = 0) const uint img_width = 0;
layout(constant_id = 1) const uint img_height = 0;

layout(push_constant) uniform PushConstant {
    uint jfa_id;
    uint sdf_id;
} pushConstants;

layout(local_size_x = 8, local_size_y = 8) in;
layout(binding = 0) uniform image2D storageImagesF[];
layout(binding = 0) uniform iimage2D storageImagesI[];
layout(binding = 0) uniform uimage2D storageImagesU[];

struct Material {
    vec3 color;
    float radiance;
};

layout(binding = 1) readonly buffer MaterialBuffer { Material materials[]; } storageBuffers[];

void main() {
    ivec2 local = ivec2(gl_GlobalInvocationID.xy);
    if (any(greaterThanEqual(local, ivec2(img_width, img_height)))) return;
    ivec2 seed = ivec2(imageLoad(storageImagesI[pushConstants.jfa_id], local).xy);
    float dist = distance(vec2(local), vec2(seed));
    float t = pow(clamp(1.0 - dist / 100.0, 0.0, 1.0), 2);

    uint drawn = imageLoad(storageImagesU[0], local).x;
    Material material = storageBuffers[0].materials[drawn];

    imageStore(storageImagesF[pushConstants.sdf_id], local, vec4(material.color * material.radiance * t, 1.0));
}