#version 450
#extension GL_EXT_shader_image_load_formatted : require
#extension GL_EXT_nonuniform_qualifier : require

layout(constant_id = 0) const uint img_width = 0;
layout(constant_id = 1) const uint img_height = 0;

layout(push_constant) uniform PushConstant {
    uint jfa_id;
    uint sdf_id;
} pushConstants;

layout(local_size_x = 8, local_size_y = 8) in;
layout(binding = 0) uniform image2D storageImagesF[];
layout(binding = 0) uniform iimage2D storageImagesI[];

void main() {
    ivec2 local = ivec2(gl_GlobalInvocationID.xy);
    if (any(greaterThanEqual(local, ivec2(img_width, img_height)))) return;

    ivec2 seed = ivec2(imageLoad(storageImagesI[pushConstants.jfa_id], local).xy);
    float dist = distance(vec2(local), vec2(seed));
    imageStore(storageImagesF[pushConstants.sdf_id], local, vec4(dist));
}