#pragma once
#include <filesystem>
#include <string>
#include "framework/util/flat_hash_map.hpp"

// this system was partly generated by claude AI

enum class FileError {
    None,
    NotFound,
    NotAFile,
    UnknownMount,
    ReadFailed,
};

template<class T>
struct Result {
    T value{};
    FileError error = FileError::None;

    [[nodiscard]] bool ok() const { return error == FileError::None; }
    explicit operator bool() const { return ok(); }
    T& operator*() { return value; }
    const T& operator*() const { return value; }
};

class FileSystem {
public:
    void add_route( std::string name, const std::filesystem::path& path );
    void remove_route( const std::string& name );
    void set_root( std::filesystem::path path ) { root_ = std::move(path); }

    [[nodiscard]] Result<std::filesystem::path> resolve( std::string_view virtual_path ) const;
    [[nodiscard]] bool exists( std::string_view virtual_path ) const;
    [[nodiscard]] bool is_file( std::string_view virtual_path ) const;

    [[nodiscard]] Result<std::string> read_text( std::string_view virtual_path ) const;
    [[nodiscard]] Result<std::vector<std::byte>> read_binary( std::string_view virtual_path ) const;

    static FileError open_for_read( const std::filesystem::path& path, std::ifstream& out, std::uintmax_t& out_size );

private:
    fwrk::flat_hash_map<std::string, std::filesystem::path> uri_;
    std::filesystem::path root_;
};
